"""Focused wrappers around the native adaptive meshing core."""

from .bindings import (
    adaptive_status,
    bounding_box_contains,
    bounding_box_overlaps,
    cell_may_contain_isosurface,
    corner_sign_mask,
    morton_decode_3d,
    morton_encode_3d,
    particle_fields,
    query_cell_contributors,
    top_level_bin_counts,
    wendland_c2_gradient,
    wendland_c2_value,
)
from .pipeline import (
    compute_isovalue_from_percentile,
    fof_cluster,
    run_full_pipeline,
)
from .topology import (
    classify_occupied_solid,
    classify_occupied_solid_from_handle,
    classify_occupied_solid_from_tree,
)
from .tree import (
    build_native_tree_handle,
    build_refined_tree,
    create_child_cells,
    create_top_level_cells,
    filter_child_contributors,
    generate_mesh,
    generate_mesh_from_tree_handle,
    hermite_samples_for_cell,
    refine_octree,
    run_octree_pipeline,
    solve_qef_for_leaf,
    solve_vertices,
)

__all__ = [
    "adaptive_status",
    "bounding_box_contains",
    "bounding_box_overlaps",
    "build_native_tree_handle",
    "build_refined_tree",
    "cell_may_contain_isosurface",
    "classify_occupied_solid",
    "classify_occupied_solid_from_handle",
    "classify_occupied_solid_from_tree",
    "compute_isovalue_from_percentile",
    "corner_sign_mask",
    "create_child_cells",
    "create_top_level_cells",
    "filter_child_contributors",
    "fof_cluster",
    "generate_mesh",
    "generate_mesh_from_tree_handle",
    "hermite_samples_for_cell",
    "morton_decode_3d",
    "morton_encode_3d",
    "particle_fields",
    "query_cell_contributors",
    "refine_octree",
    "run_full_pipeline",
    "run_octree_pipeline",
    "solve_qef_for_leaf",
    "solve_vertices",
    "top_level_bin_counts",
    "wendland_c2_gradient",
    "wendland_c2_value",
]
